version: '3'
services:
  jenkins:
    container_name: jenkins
    image: tribunex/jenkins-maven:latest
    ports: 
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/settings.xml:/usr/share/java/maven-3/conf/settings.xml 
      - ${CONTAINER_STORAGE}/jenkins_home:/var/jenkins_home
      - ${CONTAINER_STORAGE}/${LIFERAY_STORAGE}:${LIFERAY_HOME}
    environment:
      - NEXUS_HOSTNAME=${NEXUS_HOSTNAME}
      - LIFERAY_HOME=${LIFERAY_HOME}
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - ${CONTAINER_STORAGE}/nexus_home:/nexus-data
  liferay:
    container_name: liferay
    image: liferay/liferay-portal:7.1.0-ga1-1.1
    ports: 
      - "8080:8080"
    volumes:
      - ${CONTAINER_STORAGE}/${LIFERAY_STORAGE}:/opt/liferay/deploy