version: '3'
services:
  liferay:
    container_name: jenkins
    image: tribunex/jenkins-maven:latest
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./settings.xml:/usr/share/java/maven-3/conf/settings.xml 
      - ../container_storage/jenkins_home:/var/jenkins_home
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - ../container_storage/nexus_home:/nexus-data
